import Mathlib

namespace KnuthFasc8AEx210

/-!
# General border criterion

The source proof uses the coordinate functional `e_pᵀ`. The argument only
needs an arbitrary linear functional that does not vanish on the certified
kernel vector, so the result is stated in that more general form.
-/

section Border

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]

/-- The function represented by the bordered matrix `[[H,v],[φ,0]]`. -/
def borderedFunction (H : V →ₗ[K] V) (v : V) (φ : V →ₗ[K] K) :
    V × K → V × K :=
  fun xc => (H xc.1 + xc.2 • v, φ xc.1)

/--
An injective border proves both conclusions needed for algebraic simplicity:
the kernel is generated by `v`, and `v` has no preimage under `H`.
-/
theorem border_kernel_generator_and_no_chain
    (H : V →ₗ[K] V) (v : V) (φ : V →ₗ[K] K)
    (hv : H v = 0) (hφv : φ v ≠ 0)
    (hborder : Function.Injective (borderedFunction H v φ)) :
    (∀ x : V, H x = 0 → ∃ c : K, x = c • v) ∧ ¬∃ x : V, H x = v := by
  constructor
  · intro x hx
    let c : K := φ x / φ v
    let y : V := x - c • v
    have hc : c * φ v = φ x := by
      dsimp [c]
      exact div_mul_cancel₀ _ hφv
    have hHy : H y = 0 := by
      dsimp [y]
      rw [map_sub, map_smul, hx, hv, smul_zero, sub_zero]
    have hφy : φ y = 0 := by
      dsimp [y]
      rw [map_sub, map_smul]
      simp only [smul_eq_mul]
      rw [hc, sub_self]
    have heq : borderedFunction H v φ (y, 0) = borderedFunction H v φ (0, 0) := by
      apply Prod.ext
      · simp [borderedFunction, hHy]
      · simp [borderedFunction, hφy]
    have hpair := hborder heq
    have hy0 : y = 0 := congrArg Prod.fst hpair
    refine ⟨c, ?_⟩
    exact sub_eq_zero.mp (by simpa [y] using hy0)
  · rintro ⟨x, hx⟩
    let c : K := φ x / φ v
    let y : V := x - c • v
    have hc : c * φ v = φ x := by
      dsimp [c]
      exact div_mul_cancel₀ _ hφv
    have hHy : H y = v := by
      dsimp [y]
      rw [map_sub, map_smul, hx, hv, smul_zero, sub_zero]
    have hφy : φ y = 0 := by
      dsimp [y]
      rw [map_sub, map_smul]
      simp only [smul_eq_mul]
      rw [hc, sub_self]
    have heq : borderedFunction H v φ (y, -1) = borderedFunction H v φ (0, 0) := by
      apply Prod.ext
      · simp [borderedFunction, hHy]
      · simp [borderedFunction, hφy]
    have hpair := hborder heq
    have hneg : (-1 : K) = 0 := congrArg Prod.snd hpair
    exact one_ne_zero (neg_eq_zero.mp hneg)

/-- The kernel part of the border criterion as a submodule equality. -/
theorem ker_eq_span_singleton_of_injective_border
    (H : V →ₗ[K] V) (v : V) (φ : V →ₗ[K] K)
    (hv : H v = 0) (hφv : φ v ≠ 0)
    (hborder : Function.Injective (borderedFunction H v φ)) :
    LinearMap.ker H = K ∙ v := by
  apply le_antisymm
  · intro x hx
    obtain ⟨c, rfl⟩ :=
      (border_kernel_generator_and_no_chain H v φ hv hφv hborder).1 x hx
    exact Submodule.smul_mem (K ∙ v) c (Submodule.subset_span (by simp))
  · apply Submodule.span_le.2
    intro x hx
    have hxv : x = v := by simpa using hx
    subst x
    exact LinearMap.mem_ker.mpr hv

/-- The certified eigenvector is not in the range of the shifted operator. -/
theorem not_mem_range_of_injective_border
    (H : V →ₗ[K] V) (v : V) (φ : V →ₗ[K] K)
    (hv : H v = 0) (hφv : φ v ≠ 0)
    (hborder : Function.Injective (borderedFunction H v φ)) :
    v ∉ LinearMap.range H := by
  intro hvRange
  rcases hvRange with ⟨x, hx⟩
  exact (border_kernel_generator_and_no_chain H v φ hv hφv hborder).2 ⟨x, hx⟩

end Border

end KnuthFasc8AEx210
